### ISSUE TITLE
Caching Vanity URL's and Ad Spaces

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/www.spee.ch#6]
Speech is **caching** vanity URL's and ad spaces from **One** to **Ten**.

This means that when someone **pays** for **ad space** on the app homepage or a **vanity URL**, Speech keeps the old file for the time specified on the server for caching instead of displaying the new content.

Typically website caching for images is between **1 month and 1 year**.

But for any dynamic pages where content changes **on the fly**, there should be only a small timeframe.

I would recommend the **caching expire limit** to be the same as the **average time** it takes for content to **write to the blockchain**.

[expires.conf](#)
```
# Media: images, icons, video, audio, HTC
location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
  expires 1M;
  access_log off;
  add_header Cache-Control "public";
}
```
Should be
```
# Media: images, icons, video, audio, HTC
location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
  expires 5m;
  access_log off;
  add_header Cache-Control "public";
}
```

**Comment by Smurphonomics** [comment]
*Also, server/stack caching management needs addressing,

**Comment by billbitt** [comment]
@Smurphonomics where do you see the `expires.conf` file? I believe the issue you are getting at is actually not related to caching of static assets on the server, but rather how spee.ch stores a copy of the blockchain and when it retrieves content from lbry based on that database.  More thoughts below...

Spee.ch doesn't actually have a cache for the responses it sends for any specific url (although this is something I think we should add).  The only caching at this point is it stores local copies of the files that pertain to the claims based on the claim name and claim id.   

So, if a _new_ claim is made to a out-bid an existing claim on a url, the correct new file and claim info should be served since it will have a new claim id.  e.g. if someone pays for ad space on the app homepage or a vanity URL, if they are making a new claim, spee.ch will get the new file and content for that claim.  

However, if an existing claim is _updated_, then you are correct spee.ch will serve updated claim content like name, etc. but will serve the old file.  I think the proper place to fix this is in the sync tool, actually.  The sync tool is what updates the mysql db that spee.ch queries to find the claim info and file info for a given url.  Another option, but somewhat hacky, would be to add a button on the page which triggers a 'refresh' of the spee.ch db.  I.e. it would trigger spee.ch to delete any file record it has and re-retrieve the file from the lbry network.

@tzarebczan fyi

**Comment by kauffj** [comment]
@Smurphonomics did you look at the response headers sent by spee.ch? They appear correct to me, so I think it just needs to be fixed in spee.ch business logic as Bill indicates.

@billbitt I think the right fix for this is along one of two (non-exclusive) thrusts:

1) Run a background task to periodically requery the blockchain data.
2) Add a facility to spee.ch that lets it observe new publishes and updates, and perform a refresh when it sees a publish related to a claim id or name it is tracking.

It's worth considering whether @beamer's work on chainquery could help with this.

**Comment by Invariant-Change** [comment]
Yes - Got confused with the blockchain syncing issue as @billbitt mentions above. So closing this one :)
